export const dummyProducts = [
  {
    _id: "1",
    areaId: "area-1",
    count_modules: 5,
    count_lesson: 25,
    count_members: 100,
    format: "SQUARE",
    name: "Curso de Programação",
    thumbnail: "images/bg2.png",
    description:
      "Aprenda os fundamentos de programação com este curso abrangente.",
    category: "Tecnologia",
    duration: "10h",
    delDate: null,
    state: "active",
    createdAt: "2025-01-01",
    updatedAt: "2025-01-15",
    modules: [
      {
        _id: "module-1",
        name: "Introdução à Programação",
        stateModule: "active",
        description: "Conheça os conceitos básicos de programação.",
        format: "SQUARE",
        lessons_count: 5,
        thumbnail: null,
      },
      {
        _id: "module-2",
        name: "Lógica de Programação",
        stateModule: "active",
        description: "Entenda como resolver problemas com lógica.",
        format: "HORIZONTAL_RECT",
        lessons_count: 7,
        thumbnail: null,
      },
      {
        _id: "module-3",
        name: "Estruturas de Dados",
        stateModule: "active",
        description: "Domine estruturas como listas, pilhas e filas.",
        format: "VERTICAL_RECT",
        lessons_count: 8,
        thumbnail: null,
      },
      {
        _id: "module-4",
        name: "Algoritmos Básicos",
        stateModule: "active",
        description: "Aprenda a implementar algoritmos clássicos.",
        format: "VERTICAL_RECT_MAX",
        lessons_count: 6,
        thumbnail: null,
      },
    ],
  },
  {
    _id: "2",
    areaId: "area-2",
    format: "HORIZONTAL_RECT",
    count_modules: 8,
    count_lesson: 40,
    count_members: 200,
    name: "Design Gráfico Completo",
    thumbnail: "images/bg2.png",
    description:
      "Aprenda as principais ferramentas e técnicas de design gráfico.",
    category: "Design",
    duration: "15h",
    delDate: null,
    state: "active",
    createdAt: "2025-01-05",
    updatedAt: "2025-01-20",
    modules: [
      {
        _id: "module-5",
        name: "Introdução ao Design",
        stateModule: "active",
        description: "Descubra os fundamentos do design.",
        format: "VERTICAL_RECT",
        lessons_count: 6,
        thumbnail: null,
      },
      {
        _id: "module-6",
        name: "Ferramentas Avançadas",
        stateModule: "active",
        description: "Aprenda a usar ferramentas como Photoshop e Illustrator.",
        format: "VERTICAL_RECT_MAX",
        lessons_count: 10,
        thumbnail: null,
      },
      {
        _id: "module-7",
        name: "Tipografia",
        stateModule: "active",
        description: "Compreenda o uso de fontes e estilos tipográficos.",
        format: "SQUARE",
        lessons_count: 5,
        thumbnail: null,
      },
      {
        _id: "module-8",
        name: "Design Responsivo",
        stateModule: "active",
        description: "Aprenda a criar designs que se adaptam a dispositivos.",
        format: "HORIZONTAL_RECT",
        lessons_count: 8,
        thumbnail: null,
      },
    ],
  },
  {
    _id: "3",
    areaId: "area-3",
    count_modules: 3,
    format: "VERTICAL_RECT",
    count_lesson: 15,
    count_members: 50,
    name: "Marketing Digital Básico",
    thumbnail: "images/bg2.png",
    description:
      "Entenda os fundamentos do marketing digital e como aplicá-los.",
    category: "Marketing",
    duration: "5h",
    delDate: null,
    state: "active",
    createdAt: "2025-01-10",
    updatedAt: "2025-01-15",
    modules: [
      {
        _id: "module-9",
        name: "Redes Sociais",
        stateModule: "active",
        description: "Saiba como criar campanhas eficientes em redes sociais.",
        format: "SQUARE",
        lessons_count: 4,
        thumbnail: null,
      },
      {
        _id: "module-10",
        name: "Anúncios Online",
        stateModule: "active",
        description: "Aprenda a criar anúncios no Google e Facebook.",
        format: "HORIZONTAL_RECT",
        lessons_count: 5,
        thumbnail: null,
      },
      {
        _id: "module-11",
        name: "SEO Básico",
        stateModule: "active",
        description: "Descubra como melhorar o ranqueamento no Google.",
        format: "VERTICAL_RECT",
        lessons_count: 7,
        thumbnail: null,
      },
      {
        _id: "module-12",
        name: "E-mail Marketing",
        stateModule: "active",
        description: "Estratégias para campanhas de e-mail eficazes.",
        format: "VERTICAL_RECT_MAX",
        lessons_count: 6,
        thumbnail: null,
      },
    ],
  },
  {
    _id: "4",
    areaId: "area-3",
    count_modules: 3,
    format: "VERTICAL_RECT_MAX",
    count_lesson: 15,
    count_members: 50,
    name: "E-commerce Avançado",
    thumbnail: "images/bg2.png",
    description:
      "Aprenda técnicas avançadas para gerir e otimizar sua loja online.",
    category: "E-commerce",
    duration: "8h",
    delDate: null,
    state: "active",
    createdAt: "2025-01-15",
    updatedAt: "2025-01-20",
    modules: [
      {
        _id: "module-13",
        name: "Gestão de Produtos",
        stateModule: "active",
        description: "Como organizar e gerenciar produtos no e-commerce.",
        format: "VERTICAL_RECT",
        lessons_count: 6,
        thumbnail: null,
      },
      {
        _id: "module-14",
        name: "Técnicas de Conversão",
        stateModule: "active",
        description: "Otimize seu site para aumentar as vendas.",
        format: "HORIZONTAL_RECT",
        lessons_count: 5,
        thumbnail: null,
      },
      {
        _id: "module-15",
        name: "Integração com Marketplaces",
        stateModule: "active",
        description: "Venda seus produtos em plataformas como Amazon e eBay.",
        format: "VERTICAL_RECT_MAX",
        lessons_count: 8,
        thumbnail: null,
      },
      {
        _id: "module-16",
        name: "Análise de Dados",
        stateModule: "active",
        description: "Use dados para tomar decisões inteligentes.",
        format: "SQUARE",
        lessons_count: 7,
        thumbnail: null,
      },
    ],
  },
];
